# Generated by Django 5.2.6 on 2026-02-24 17:30

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(blank=True, max_length=550, null=True, verbose_name='Источник')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='blogs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('cover', models.FileField(blank=True, default='default/blogs/cover.png', null=True, upload_to='blogs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка')),
                ('image', models.FileField(blank=True, default='default/blogs/cover.png', null=True, upload_to='blogs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='CategorysBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка категории')),
                ('icon', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Иконка категории')),
                ('image', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Картинка категории')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новости',
            },
        ),
        migrations.CreateModel(
            name='TagsBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover', models.FileField(blank=True, null=True, upload_to='tags/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка метки')),
                ('icon', models.FileField(blank=True, null=True, upload_to='tags/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Иконка метки')),
                ('image', models.FileField(blank=True, null=True, upload_to='tags/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Картинка метки')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='tags/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Метка новости',
                'verbose_name_plural': 'Метки новости',
            },
        ),
    ]
