# Generated by Django 5.2.6 on 2026-03-16 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='categorysblogs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blogs.categorysblogs', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ManyToManyField(blank=True, to='blogs.categorysblogs', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='likesblogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='likesblogs',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blogs.blogs', verbose_name='Блог'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tagsblogs', verbose_name='Метки'),
        ),
        migrations.AddConstraint(
            model_name='likesblogs',
            constraint=models.UniqueConstraint(fields=('author', 'blog'), name='unique_author_blog_like'),
        ),
    ]
