# Generated by Django 5.2.6 on 2026-03-16 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя контакта')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('telegram', 'Telegram'), ('other', 'Другое')], default='email', max_length=50, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=255, verbose_name='Значение (email/телефон/etc)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название списка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Список контактов',
                'verbose_name_plural': 'Списки контактов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MassMailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('recipient_emails', models.TextField(blank=True, help_text='Email адреса через запятую или по одному в строке', verbose_name='Email получателей')),
                ('recipient_file', models.FileField(blank=True, null=True, upload_to='mailing_lists/%Y/%m/', verbose_name='Файл со списком рассылки')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Средний'), ('high', 'Высокий')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отправителя')),
                ('from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя отправителя')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('opened_count', models.IntegerField(default=0, verbose_name='Открыто')),
                ('clicked_count', models.IntegerField(default=0, verbose_name='Переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Кампания массовой рассылки',
                'verbose_name_plural': 'Кампании массовой рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время перехода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лог массовой рассылки',
                'verbose_name_plural': 'Логи массовой рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('custom_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер сообщения')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.TextField(blank=True, help_text='Введите email адреса через запятую. Например: user1@example.com, user2@example.com', verbose_name='Получатели (email адреса)')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('subject', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Тема')),
                ('message_type', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее'), ('draft', 'Черновик')], default='outgoing', max_length=20, verbose_name='Тип сообщения')),
                ('self_field', models.BooleanField(default=False, verbose_name='Для себя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Директория сообщений',
                'verbose_name_plural': 'Директории сообщений',
            },
        ),
        migrations.CreateModel(
            name='MessageDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Директория сообщений',
                'verbose_name_plural': 'Директории сообщений',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_files/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файл сообщения',
                'verbose_name_plural': 'Файлы сообщений',
            },
        ),
        migrations.CreateModel(
            name='MessageMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.TextField(verbose_name='Маска')),
            ],
            options={
                'verbose_name': 'Маска сообщения',
                'verbose_name_plural': 'Маски сообщений',
            },
        ),
        migrations.CreateModel(
            name='MessageRm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Удаленное сообщение',
                'verbose_name_plural': 'Удаленные сообщения',
            },
        ),
        migrations.CreateModel(
            name='UserSettingsSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_header', models.TextField(blank=True, null=True, verbose_name='Шапка сообщения письма')),
                ('message_footer', models.TextField(blank=True, null=True, verbose_name='Подвал сообщения письма')),
                ('email_host', models.TextField(blank=True, null=True, verbose_name='Email Site HOST')),
                ('default_from_email', models.TextField(blank=True, null=True, verbose_name='Email Site HOST')),
                ('email_port', models.TextField(blank=True, null=True, verbose_name='Email Site PORT')),
                ('email_host_user', models.TextField(blank=True, null=True, verbose_name='Email Site User')),
                ('email_host_password', models.TextField(blank=True, null=True, verbose_name='Email Site Password')),
                ('email_use_tls', models.BooleanField(blank=True, default=False, null=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(blank=True, default=False, null=True, verbose_name='Use SSL')),
            ],
            options={
                'verbose_name': 'Настройка почты',
                'verbose_name_plural': 'Настройки почты',
            },
        ),
    ]
