# Generated by Django 5.2.6 on 2026-03-16 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mail.contactlist', verbose_name='Список контактов'),
        ),
        migrations.AddField(
            model_name='massmailcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_mail_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='massmaillog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mail.massmailcampaign', verbose_name='Кампания'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано пользователями'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='messagedir',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_dirs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='message',
            name='dirs',
            field=models.ManyToManyField(blank=True, related_name='messages', to='mail.messagedir', verbose_name='Директории'),
        ),
        migrations.AddField(
            model_name='messagedirectory',
            name='user',
            field=models.ManyToManyField(related_name='message_directory', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mail.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='messagemask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_masks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='message',
            name='masks',
            field=models.ManyToManyField(blank=True, related_name='messages', to='mail.messagemask', verbose_name='Маски'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mail.messagerm', verbose_name='Связанное удаленное сообщение'),
        ),
        migrations.AddField(
            model_name='usersettingssmtp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massmailcampaign',
            name='use_smtp_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.usersettingssmtp', verbose_name='SMTP настройки'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlist',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('contact_list', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='messagedir',
            unique_together={('name', 'user')},
        ),
    ]
