# Generated by Django 5.2.6 on 2026-03-16 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('anonce', models.CharField(blank=True, max_length=250, null=True, verbose_name='Отрывок')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='projects/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('cover', models.FileField(blank=True, default='default/projects/cover.png', null=True, upload_to='projects/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка')),
                ('image', models.FileField(blank=True, default='default/projects/cover.png', null=True, upload_to='projects/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='CategorysProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('fragment', models.TextField(blank=True, null=True, verbose_name='отрывок')),
                ('cover', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка категории')),
                ('icon', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Иконка категории')),
                ('image', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Картинка категории')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.categorysprojects', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
            },
        ),
    ]
