# Generated by Django 5.2.6 on 2026-02-24 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Новое'), (1, 'Обратная связь'), (2, 'В процессе'), (3, 'Решенный'), (4, 'Закрытый')], default=0, verbose_name='Статус')),
                ('themas', models.TextField(verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Заказчик'), (1, 'Поддержка')], default=1, editable=False, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий тикета',
                'verbose_name_plural': 'Комментарии тикета',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket/%Y/%m/%d/tiket_file/')),
            ],
            options={
                'verbose_name': 'Файл комментария тикета',
                'verbose_name_plural': 'Файлы комментариев тикета',
            },
        ),
    ]
