# Generated by Django 5.2.6 on 2026-02-24 17:30

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='contact/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('title', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=550, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страница контакты',
                'verbose_name_plural': 'Страницы контакты',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, default=' ', null=True, verbose_name='Ответ')),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопрос',
            },
        ),
        migrations.CreateModel(
            name='SettingsGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Логотип')),
                ('doplogo', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный логотип')),
                ('logo_white', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Логотип белый')),
                ('doplogo_white', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный логотип белый')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Фавикон')),
                ('paymentmetod', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Методы оплаты')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='Копирайт')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('message_header', models.TextField(blank=True, null=True, verbose_name='Шапка сообщения письма')),
                ('message_footer', models.TextField(blank=True, null=True, verbose_name='Подвал сообщения письма')),
                ('yandex_metrica', models.TextField(blank=True, null=True, verbose_name='Яндекс метрика')),
                ('google_analitic', models.TextField(blank=True, null=True, verbose_name='Гугл аналитика')),
                ('email_host', models.TextField(blank=True, null=True, verbose_name='Email Site HOST')),
                ('default_from_email', models.TextField(blank=True, null=True, verbose_name='Email Site HOST')),
                ('email_port', models.TextField(blank=True, null=True, verbose_name='Email Site PORT')),
                ('email_host_user', models.TextField(blank=True, null=True, verbose_name='Email Site User')),
                ('email_host_password', models.TextField(blank=True, null=True, verbose_name='Email Site Password')),
                ('email_use_tls', models.BooleanField(blank=True, default=False, null=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(blank=True, default=False, null=True, verbose_name='Use SSL')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ContactPageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('Номера телефонов', [('phone_default', 'Номер телефона по умолчанию'), ('phone', 'Остальные номера телефонов')]), ('Карты', [('map_default', 'Карта по умолчанию'), ('map', 'Остальные карты')]), ('Адресса', [('address_default', 'Адресс по умолчанию'), ('address', 'Остальные адресса')]), ('Электроная почта', [('email_default', 'Почта по умолчанию'), ('email', 'Остальные почты')])], max_length=50, verbose_name='Тип')),
                ('image', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='contact/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('title_contact', models.CharField(max_length=350, verbose_name='Заголовок контактов')),
                ('description_contact', models.CharField(max_length=550, verbose_name='Описание контактов')),
                ('information_contact', models.CharField(max_length=350, verbose_name='Информация контактов')),
                ('contact_pages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_page', to='webmain.contactpage', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Страница контакты (информация)',
                'verbose_name_plural': 'Страницы контакты (информация)',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Новости'), (2, 'Поиск'), (3, 'Контакты'), (4, 'ЧаВО'), (5, 'Авторизация'), (6, 'Регистрация'), (7, 'Сбросить пароль'), (8, 'Профиль'), (9, 'Сменить пароль'), (10, 'Паспортные данные'), (11, 'Уведомление')], default=1, unique=True, verbose_name='Странца')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Сео страницы',
                'verbose_name_plural': 'Сео страниц',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='текст')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страницы',
            },
        ),
        migrations.AddField(
            model_name='contactpage',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='текст')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Страница О нас',
                'verbose_name_plural': 'Страницы О нас',
            },
        ),
    ]
