# Generated by Django 5.2.6 on 2026-02-24 17:37

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Стандартная'), (2, 'Пользовательское соглашение'), (3, 'Политика конфедециальности'), (4, 'Политика Cookie - Файлов'), (5, 'Согласия на обработку персональных данных')], default=1, verbose_name='Тип')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='pages/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('metadescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('publishet', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='SettingsSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_header', models.TextField(blank=True, null=True, verbose_name='Шапка сообщения письма')),
                ('message_footer', models.TextField(blank=True, null=True, verbose_name='Подвал сообщения письма')),
                ('email_host', models.TextField(blank=True, null=True, verbose_name='Email Site HOST')),
                ('default_from_email', models.TextField(blank=True, null=True, verbose_name='Email Site HOST')),
                ('email_port', models.TextField(blank=True, null=True, verbose_name='Email Site PORT')),
                ('email_host_user', models.TextField(blank=True, null=True, verbose_name='Email Site User')),
                ('email_host_password', models.TextField(blank=True, null=True, verbose_name='Email Site Password')),
                ('email_use_tls', models.BooleanField(blank=True, default=False, null=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(blank=True, default=False, null=True, verbose_name='Use SSL')),
            ],
            options={
                'verbose_name': 'Настройка почты',
                'verbose_name_plural': 'Настройки почты',
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='contactpageinformation',
            name='contact_pages',
        ),
        migrations.DeleteModel(
            name='Faqs',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='email_use_tls',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='message_footer',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='message_header',
        ),
        migrations.RemoveField(
            model_name='settingsglobale',
            name='paymentmetod',
        ),
        migrations.AlterField(
            model_name='contactpageinformation',
            name='page_type',
            field=models.CharField(choices=[('Карты', [('map_default', 'Карта по умолчанию'), ('map', 'Остальные карты')]), ('Номера телефонов', [('phone_default', 'Номер телефона по умолчанию'), ('phone', 'Остальные номера телефонов')]), ('Электроная почта', [('email_default', 'Почта по умолчанию'), ('email', 'Остальные почты')]), ('Адресса', [('address_default', 'Адресс по умолчанию'), ('address', 'Остальные адресса')])], max_length=50, verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
