# Generated by Django 5.2.6 on 2026-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_pages_settingssmtp_remove_aboutpage_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='keywords',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='pages',
            name='templates',
            field=models.TextField(default=1, verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactpageinformation',
            name='page_type',
            field=models.CharField(choices=[('Номера телефонов', [('phone_default', 'Номер телефона по умолчанию'), ('phone', 'Остальные номера телефонов')]), ('Электроная почта', [('email_default', 'Почта по умолчанию'), ('email', 'Остальные почты')]), ('Адресса', [('address_default', 'Адресс по умолчанию'), ('address', 'Остальные адресса')]), ('Карты', [('map_default', 'Карта по умолчанию'), ('map', 'Остальные карты')])], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='pagetype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Обычная'), (1, 'Главная'), (2, 'О нас'), (3, 'Контакты'), (4, 'Пользовательское соглашение'), (5, 'Политика конфедециальности'), (6, 'Политика Cookie - Файлов'), (7, 'Согласия на обработку персональных данных')], default=0, verbose_name='Тип'),
        ),
    ]
