# Generated by Django 5.2.6 on 2026-03-16 12:20

import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.TextField(verbose_name='Электронная почта')),
                ('subject', models.TextField(verbose_name='Обьект сотрудничества')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запрос на сотрудничество',
                'verbose_name_plural': 'Запросы на сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Статистика', [('statistic_generate', 'Генерация'), ('statistic_view', 'Просмотр')]), ('Группы', [('groups_list', 'Список'), ('groups_create', 'Создание'), ('groups_edit', 'Редактирование'), ('groups_delete', 'Удаление')]), ('Сотрудники', [('employees_list', 'Список'), ('employees_create', 'Создание'), ('employees_edit', 'Редактирование'), ('employees_delete', 'Удаление')]), ('Клиенты', [('clients_list', 'Список'), ('clients_create', 'Создание'), ('clients_edit', 'Редактирование'), ('clients_delete', 'Удаление')]), ('База знаний', [('knowledge_list', 'Список'), ('knowledge_create', 'Создание'), ('knowledge_edit', 'Редактирование'), ('knowledge_delete', 'Удаление')]), ('Пользователи', [('clients_list', 'Список'), ('clients_create', 'Создание'), ('clients_edit', 'Редактирование'), ('clients_delete', 'Удаление')]), ('Email', [('email_send', 'Отправка'), ('email_list', 'Список')]), ('Телефония', [('telephony_list', 'Список'), ('telephony_call', 'Звонок')]), ('Проекты', [('projects_list', 'Список'), ('projects_create', 'Создание'), ('projects_edit', 'Редактирование'), ('projects_delete', 'Удаление')]), ('Проделаные работы', [('works_list', 'Список')]), ('График', [('schedule_view', 'Просмотр'), ('schedule_edit', 'Редактирование')]), ('Задачник', [('tasks_list', 'Список'), ('tasks_create', 'Создание'), ('tasks_edit', 'Редактирование'), ('tasks_delete', 'Удаление')]), ('Бухгалтерия', [('accounting_view', 'Просмотр')]), ('Платежи', [('payments_list', 'Список'), ('payments_create', 'Создание')]), ('Запросы', [('requests_list', 'Список')]), ('Хоз.часть', [('admin_part_view', 'Просмотр')]), ('Урок', [('lesson_list', 'Список')]), ('Обучение', [('training_list', 'Список')]), ('Вакансии', [('vacancies_list', 'Список'), ('vacancies_create', 'Создание'), ('vacancies_edit', 'Редактирование'), ('vacancies_delete', 'Удаление')]), ('Заявки', [('applications_list', 'Список'), ('applications_create', 'Создание')]), ('Склады (Магазины)', [('storages_list', 'Список'), ('storages_create', 'Создание'), ('storages_edit', 'Редактирование'), ('storages_delete', 'Удаление')]), ('Компании', [('companies_list', 'Список'), ('companies_create', 'Создание')]), ('Товары', [('products_list', 'Список'), ('products_create', 'Создание'), ('products_edit', 'Редактирование'), ('products_delete', 'Удаление')]), ('Бренды', [('brends_list', 'Список'), ('brends_create', 'Создание'), ('brends_edit', 'Редактирование'), ('brends_delete', 'Удаление')]), ('Категории', [('categories_list', 'Список'), ('categories_create', 'Создание')]), ('Покупки', [('purchases_list', 'Список')]), ('Жалобы', [('complaints_list', 'Список')]), ('Отзывы', [('reviews_list', 'Список')]), ('Комментарии', [('comments_list', 'Список')]), ('Вопросы', [('questions_list', 'Список')]), ('Вариации', [('variations_list', 'Список')]), ('Валюта', [('currency_list', 'Список')]), ('Поддержка', [('support_list', 'Список')]), ('Тикеты', [('tickets_list', 'Список')]), ('Обращение', [('requests_view', 'Просмотр')]), ('Домены', [('domains_list', 'Список'), ('domains_create', 'Создание')]), ('Програма лояльности', [('loyalty_list', 'Список')]), ('Уведомления', [('notifications_list', 'Список')]), ('Языки', [('languages_list', 'Список')]), ('Интеграции', [('integrations_list', 'Список')]), ('Блог (Новости)', [('blog_list', 'Список')]), ('Страницы', [('pages_list', 'Список')]), ('Благотворительность', [('charity_list', 'Список')]), ('Галерея', [('gallery_list', 'Список')]), ('Услуги', [('services_list', 'Список')]), ('Прайс', [('price_list', 'Список')]), ('ЧаВо', [('faq_list', 'Список')]), ('Документация', [('docs_list', 'Список')]), ('Личные', [('personal_view', 'Просмотр')]), ('Профиль', [('profile_view', 'Просмотр')]), ('Начисления', [('charges_list', 'Список')])], default=list, max_length=5555, null=True, verbose_name='Доступ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Stopwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Стоп слова')),
            ],
            options={
                'verbose_name': 'Стоп слово',
                'verbose_name_plural': 'Стоп слова',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Email')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
