# Generated by Django 5.2.6 on 2026-02-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.TextField(verbose_name='Электронная почта')),
                ('subject', models.TextField(verbose_name='Обьект сотрудничества')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запрос на сотрудничество',
                'verbose_name_plural': 'Запросы на сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Stopwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Стоп слова')),
            ],
            options={
                'verbose_name': 'Стоп слово',
                'verbose_name_plural': 'Стоп слова',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Email')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Notificationgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('message', models.TextField()),
                ('slug', models.TextField(editable=False)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('blogs', 'pages', 'categorysblogs', 'tagsblogs')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Груповое уведомление',
                'verbose_name_plural': 'Груповые уведомления',
            },
        ),
    ]
