# Generated by Django 5.2.6 on 2026-03-16 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groupsuser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
