# Generated by Django 5.2.6 on 2026-03-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Регистрация'), (2, 'Покупка'), (3, 'Сбросить пароль'), (4, 'Поддержка')], default=1, unique=True, verbose_name='Тип')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не прочитан'), (2, 'Прочитан')], default=1, verbose_name='Статус')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('message', models.TextField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('blogs', 'pages', 'categorysblogs', 'tagsblogs')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомление',
            },
        ),
    ]
