# Generated by Django 5.2.6 on 2026-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
                ('company_director', models.CharField(blank=True, max_length=100, null=True, verbose_name='Руководитель')),
                ('company_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юридический адрес')),
                ('company_nalogovaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Налоговый орган')),
                ('company_ogrn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН')),
                ('company_inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('company_kpp', models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП')),
                ('company_data_registration', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('company_type_activity', models.TextField(blank=True, null=True, verbose_name='Основной вид деятельности')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
